<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Template &middot; Bootstrap</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->
    <link href="<?php echo _static_url('css/bootstrap.min.css') ?>" rel="stylesheet">
    <style type="text/css">
      body {
        padding-top: 20px;
        padding-bottom: 40px;
      }

      /* Custom container */
      .container-narrow {
        margin: 0 auto;
        max-width: 700px;
      }
      .container-narrow > hr {
        margin: 30px 0;
      }
    </style>

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="../assets/js/html5shiv.js"></script>
    <![endif]-->

    <!-- Fav and touch icons -->
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="../assets/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="../assets/ico/apple-touch-icon-114-precomposed.png">
      <link rel="apple-touch-icon-precomposed" sizes="72x72" href="../assets/ico/apple-touch-icon-72-precomposed.png">
                    <link rel="apple-touch-icon-precomposed" href="../assets/ico/apple-touch-icon-57-precomposed.png">
                                   <link rel="shortcut icon" href="../assets/ico/favicon.png">
  </head>

  <body>

    <div class="container-narrow">

      <div class="masthead">
        <h3 class="muted">Todo list</h3>
      </div>

      <hr>

      <div class="row-fluid">
        <form method="post">
          <ul>
            <?php foreach ($this->list as $id => $entry): ?>
              <li class="todo" data-id="<?php echo $id ?>">
                <input type="checkbox" name="done[<?php echo $id ?>]" <?php echo $entry->is_done ? 'checked' : '' ?>>
                <a class="" href="?del=<?php echo $id ?>"><i class="icon-check"></i></a>
                <input class="auto_submit" type="text" name="entry[<?php echo $id ?>]" value="<?php echo $entry->title ?>">
                <a class="" href="?del=<?php echo $id ?>"><i class="icon-remove"></i></a>
              </li>
            <?php endforeach ?>
            <li class="add">
              <input type="checkbox" >
              <input class="" type="text" name="title" value="" placeholder="add new todo">
            </li>
          </ul>
          <input style="visibility:hidden" type="submit">
        </form>
      </div>

      <hr>

      <div class="footer">
        <p>&copy; Company 2013</p>
      </div>

    </div> <!-- /container -->

    <script type="text/javascript" src="http://code.jquery.com/jquery-1.9.1.min.js"></script>
    <script type="text/javascript">
    $(function () {
      var todo_add = function (entry, input) {
        var title = input.val();
        $.post(
          '/add',
          {
            title: title
          },
          function (ret) {
            entry.removeClass('add');
          },
          'json'
        );
      };
      var todo_edit = function (entry, input) {
        var title = input.val();
        var id = entry.data('id');
        $.post(
          '/'+id+'/edit',
          {
            title: title
          },
          function (ret) {
            console.log('edit ok');
          },
          'json'
        );
      };
      $('li.add').each(function () {
        var li = $(this);
        li.find('input[type=text]').keyup(function (e) {
          if (e.keyCode === 13) {
            todo_add(li, $(this));
          };
        }).on('change', function () {
          todo_add(li, $(this));
        });
      });
      $('li.todo').each(function () {
        var li = $(this);
        li.find('input[type=text]').on('change', function () {
          todo_edit(li, $(this));
        });
      });
    });
    </script>
  </body>
</html>

