<?php $entry = isset($entry) ? $entry : $this->entry; ?>
<?php $id = isset($id) ? $id : $this->entry->id; ?>
<li class="todo" data-id="<?php echo $id ?>">
  <input type="checkbox" name="done[<?php echo $id ?>]" <?php echo $entry->is_done ? 'checked' : '' ?> onchange="entryToggle(this);">
  <input class="auto_submit" type="text" name="entry[<?php echo $id ?>]" value="<?php echo $entry->title ?>"  onchange="entryEdit(this);">
  <a class="del-btn" href="javascript:;" onclick="entryDel(this);"><i class="icon-remove"></i></a>
</li>
